### read
get http://localhost:3000/players

### read by id
get http://localhost:3000/players/apcj3hklbge9fnr-

### delete
delete http://localhost:3000/players/apcj3hklbge9fnr

### post
post http://localhost:3000/players
Content-Type: application/json

{
    "name": "Ronaldó",
    "qualification": 5,
    "position": "csatár",
    "club": "Sehol",
    "age": 37,
    "nationality": "Portugál"
}

### put
put http://localhost:3000/players/apcj3hklbge9fnr
Content-Type: application/json

{
    "name": "Ronaldó",
    "qualification": 5,
    "position": "csatár",
    "club": "Sehol",
    "age": 37,
    "nationality": "Portugál"
}
